### ISSUE TITLE
Have some proposal 😄

### ISSUE THREAD

**Issue by caoxiemeihao** [yanquanfahei/vite-ts-vue3-admin#6]
1. 这种全局注册的写法在 TSX 下并不好
https://github.com/front-end-study-program/vite-ts-vue3-admin/blob/afc0b996824672a0f40d03653c316bd534fb13cd/src/layout/BaseLayout/index.tsx#L22

最好还是通过显式引入，能方便友好的 tree-shake，还有健全的 ts 提示
```tsx
import { Layout } from 'ant-design-vue';

<Layout>{...}</Layout>
```

**Comment by yanquanfahei** [comment]
> 1. 这种全局注册的写法在 TSX 下并不好
>    https://github.com/front-end-study-program/vite-ts-vue3-admin/blob/afc0b996824672a0f40d03653c316bd534fb13cd/src/layout/BaseLayout/index.tsx#L22
> 
> 最好还是通过显式引入，能方便友好的 tree-shake，还有健全的 ts 提示
> 
> ```tsx
> import { Layout } from 'ant-design-vue';
> 
> <Layout>{...}</Layout>
> ```

旺哥嘿嘿，
1. 我其实在 [vite-ts-vue3-admin/src/antd-ui/index.ts](https://github.com/front-end-study-program/vite-ts-vue3-admin/blob/afc0b996824672a0f40d03653c316bd534fb13cd/src/antd-ui/index.ts) 这个文件中以显示引入注册的方式去做的。这种方式和你说的这种有什么区别嘛。
2. 确实这种方式组件的 ts 提示是个问题。

**Comment by caoxiemeihao** [comment]
1. 精准 TS 提示问题
2. Tree Shaking 友好(很重要)
3. 不会导致 `src/antd-ui` 特别大，能精准分摊大小到各个组件上(基于Tree Shaking)

**Comment by yanquanfahei** [comment]
> 1. 精准 TS 提示问题
> 2. Tree Shaking 友好(很重要)
> 3. 不会导致 `src/antd-ui` 特别大，能精准分摊大小到各个组件上(基于Tree Shaking)

我明白了，感谢旺哥的建议~
